sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t swissjoshua/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swissjoshua/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-877754888128"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
