sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t swissjoshua/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swissjoshua/docker-react npm run test -- --coverage
